name: Terraform Run

on: workflow_dispatch

jobs:
  terraform-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init
        - uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.4.6
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform fmt
          -  id: fmt
            run: terraform fmt -check
            continue-on-error: true

        - name: Terraform Init
          - id: init
            run: terraform init

        - name: Terraform Validate
          - id: validate
            run: terraform validate -no-color

        - run: terraform plan
          - id: plan
            run: terraform plan -no-color
            continue-on-error: true
