---
name: Terraform R2 Run

on: workflow_dispatch


env: 
  env_var: ${{ vars.ENV_AWS_DEFAULT_REGION }}

jobs:
  terraform-run:
    runs-on: ubuntu-latest
    strategy:
      matrix: { env: ["demo1"] }
    environment: ${{ matrix.env }}
    defaults:
      run:
        working-directory: "./${{ matrix.env }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - run: terraform init
      - id: plan
        run: terraform plan -no-color 
        env:
          TF_VAR_CF_R2_ACCESS_KEY_ID: "${{ secrets.CF_R2_ACCESS_KEY_ID }}"
          TF_VAR_CF_R2_SECRET_ACCESS_KEY: "${{ secrets.CF_R2_SECRET_ACCESS_KEY }}"
          TF_VAR_CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
          TF_VAR_AWS_REGION: "${{ secrets.AWS_REGION }}"
      
      - id: apply
        run: terraform apply --auto-approve 
        env:
          TF_VAR_CF_R2_ACCESS_KEY_ID: "${{ secrets.CF_R2_ACCESS_KEY_ID }}"
          TF_VAR_CF_R2_SECRET_ACCESS_KEY: "${{ secrets.CF_R2_SECRET_ACCESS_KEY }}"
          TF_VAR_CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
          TF_VAR_AWS_REGION: "${{ secrets.AWS_REGION }}"
