name: Terraform Action to Create an R2 Bucket

on: workflow_dispatch

jobs:
  terraform-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init
        - uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.4.2
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        - run: terraform init

          - id: plan
            run: terraform plan -no-color

          - run: echo ${{ steps.plan.outputs.stdout }}
          - run: echo ${{ steps.plan.outputs.stderr }}
          - run: echo ${{ steps.plan.outputs.exitcode }}
